language: php
php:
  - 8.0
  - nightly
matrix:
  fast_finish: true
  allow_failures:
    - php: nightly
before_install:
  - travis_wait composer start-db > /dev/null &
install:
  - composer install --no-interaction --prefer-source
script:
  - composer test
